# Use the official Python base image
FROM python:3.9

# Set the working directory in the container
WORKDIR /app

# Copy the requirements.txt file to the container
COPY output-processor/requirements.txt .

# Install the Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy libs
COPY lib/baseprocessor.py /app/

# Copy the rest of the application code to the container

COPY output-processor/app.py .

COPY docker-entrypoint.sh /app/
COPY wait-for-it.sh /app/

RUN chmod +xr ./wait-for-it.sh ./docker-entrypoint.sh
ENTRYPOINT ["./docker-entrypoint.sh"]
# Set the command to run the application
CMD [ "python", "app.py" ]