# Use the official Python base image
FROM wmoim/dim_eccodes_baseimage:2.28.0 

ENV DEBIAN_FRONTEND="noninteractive" \
    TZ="Etc/UTC" \
    ECCODES_DIR=/opt/eccodes \
    PATH="${PATH}:/opt/eccodes/bin"

RUN echo "Acquire::Check-Valid-Until \"false\";\nAcquire::Check-Date \"false\";" | cat > /etc/apt/apt.conf.d/10no--check-valid-until \
    && apt-get update -y \
    && apt-get install -y ${BUILD_PACKAGES} libudunits2-0 python3 python3-pip git\
    && apt-get remove --purge -y ${BUILD_PACKAGES} \
    && apt autoremove -y  \
    && apt-get -q clean \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install git+https://github.com/wmo-im/bufr2geojson.git@v0.5.0

# Set the working directory in the container
WORKDIR /app

# Install the Python dependencies
RUN pip install --no-cache-dir confluent-kafka prometheus-client

# Copy libs
COPY lib/baseprocessor.py /app/

# Copy the rest of the application code to the container

COPY decoding-processor/app.py .

COPY docker-entrypoint.sh /app/
COPY wait-for-it.sh /app/

RUN chmod +xr ./wait-for-it.sh ./docker-entrypoint.sh
ENTRYPOINT ["./docker-entrypoint.sh"]
# Set the command to run the application
CMD [ "python3", "app.py" ]